server:
  port: 8002

spring:
  main:
    banner-mode: off
    web-application-type: servlet
  application:
    name: grpc-rest-server
  config:
      import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8889/admin
      name: grpc-rest-server

# Management #
management:
  server:  
    ssl:
      enabled: false
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health,info,refresh,env

logging:
  level:
    root: INFO
    org.springframework.web: TRACE
  file:
    path: ./logs
    name: grpc-rest-server.log
    
grpc:
  client:
    grpc-auth-server:
      address: 'discovery:///grpc-auth-server'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiation-type: PLAINTEXT


# Eureka #
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.ip-address:localhost}:${eureka.port:8761}/eureka/
  instance:
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    prefer-ip-address: true     
  server:
    enableSelfPreservation: true
    waitTimeInMsWhenSyncEmpty: 0 
    response-cache-update-interval-ms: 1000
    peer-eureka-nodes-update-interval-ms: 60000  


# ribbon:
#   eager-load:
#     enabled: true
#     clients:
#     - auth-server