grpc:
  server:
    port: 9898

# Management #
management:
  server:  
    ssl:
      enabled: false
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: health,info,refresh,env

logging:
  level:
    root: INFO
    "[org.springframework.web]": TRACE

# Eureka #
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.ip-address:39.117.41.75}:${eureka.port:8761}/eureka/
  instance:
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    prefer-ip-address: true