// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: token.proto

package net.grpc.lib;

public interface TokenReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TokenReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string accessToken = 1;</code>
   * @return The accessToken.
   */
  java.lang.String getAccessToken();
  /**
   * <code>string accessToken = 1;</code>
   * @return The bytes for accessToken.
   */
  com.google.protobuf.ByteString
      getAccessTokenBytes();

  /**
   * <code>uint64 expiresIn = 2;</code>
   * @return The expiresIn.
   */
  long getExpiresIn();
}
