// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: token.proto

package net.grpc.lib;

public final class TokenProto {
  private TokenProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TokenReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TokenReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013token.proto\",\n\014TokenRequest\022\n\n\002id\030\001 \001(" +
      "\t\022\020\n\010password\030\002 \001(\t\"4\n\nTokenReply\022\023\n\013acc" +
      "essToken\030\001 \001(\t\022\021\n\texpiresIn\030\002 \001(\00425\n\005Tok" +
      "en\022,\n\014requestToken\022\r.TokenRequest\032\013.Toke" +
      "nReply\"\000B\034\n\014net.grpc.libB\nTokenProtoP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TokenRequest_descriptor,
        new java.lang.String[] { "Id", "Password", });
    internal_static_TokenReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TokenReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TokenReply_descriptor,
        new java.lang.String[] { "AccessToken", "ExpiresIn", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
